### ISSUE TITLE
 Limit RTAMO attribution to www referrals

### ISSUE THREAD

**Issue by diox** [mozilla-services/stubattribution#105]
Like in https://github.com/mozilla-services/go-bouncer/issues/347, we should ignore attribution for RTAMO if the referral wasn't from www.mozilla.org , using a referer header check. If the request didn't originally come from www.mozilla.org, and it contains attribution for RTAMO, the attribution should be dropped.

(browsers should maintain the original referer information through the redirects they go through, so even if the user is redirected from download.mozilla.org to stubdownloader.services.mozilla.com technically the `referer` will still be `www.mozilla.org`)

**Comment by diox** [comment]
Note that this should apply to requests to https://stubdownloader.services.mozilla.com/ but also to 
https://cdn.stubdownloader.services.mozilla.com/ - the latter has the attribution info already backed in the executable it's about to serve, so I don't know how practical this is...

**Comment by willdurand** [comment]
> Note that this should apply to requests to [stubdownloader.services.mozilla.com](https://stubdownloader.services.mozilla.com/) but also to
> [cdn.stubdownloader.services.mozilla.com](https://cdn.stubdownloader.services.mozilla.com/) - the latter has the attribution info already backed in the executable it's about to serve, so I don't know how practical this is...

IIRC cdn is S3 so assuming the stub service prevents the addition of attribution data, there is nothing specific to do because the stub service pushes the modified executable to s3 after it has modified it (so if it does not modify it the first time, S3 should not contain modified executables).
