### ISSUE TITLE
Download Token Log are Mis-labeling GA clientId and Not Recording GA visitId

### ISSUE THREAD

**Issue by SuYoungHong** [mozilla-services/stubattribution#112]
## Description

On download, we're creating a unique DL token for a download event and passing it to client side telemetry in order to attribute the new profiles. 

As part of this process, we're logging the DL token along with the corresponding Google Analytics clientId in a restricted database to be able to match GA data with attributed Firefox profiles. 

There are currently 2 issues with the current implementation: 
* 1) We're only recording Google Analytics clientId in our logs. However, we need to log **both** the clientId as well as the visitId in order to attribute (since attribution is a session level datapoint, not client level). 
* 2) We're recording the Google Analytics clientId as a `visit_id` in our logs, which is confusing. 

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "Approved designs attached to this issue"

The Download Token Log table should report both the Google Analytics clientId as well as Google Analytics visitId associated with the download event. 

The Download Token Log table should rename `visit_id` (which reports the Google Analytics clientId field) to `visitor_id`, or something less confusing.

**Comment by SuYoungHong** [comment]
This work is being tracked in Jira, closing now

https://mozilla-hub.atlassian.net/browse/SVCSE-947

**Comment by willdurand** [comment]
It'd still be good to have a public issue about this work.

**Comment by willdurand** [comment]
What we essentially need to do here is the following:

> Add a `session_id` field to the logs which will be provided by Bedrock

The reason is:

> By only collecting clientId (a client can have multiple sessions in a given period), we are unable to reliably match the download token to the actual session that generated the download. 
>
> This new measurement (sessionId) is really just fixing an oversight in the original implementation of the download token data collection. 

`clientId` above is what we call `visit_id` in this repo, sigh.
