### ISSUE TITLE
Consider removing S3 support

### ISSUE THREAD

**Issue by willdurand** [mozilla-services/stubattribution#137]
Instead of trying to update the _very_ outdated dependencies in https://github.com/mozilla-services/stubattribution/pull/136, which might have breaking changes according to the [CHANGELOG file](https://raw.githubusercontent.com/aws/aws-sdk-go/main/CHANGELOG.md), let's see if we could remove support for the S3 backend.

My understanding is that we likely never used it in production anyway. I looked into some cloudops configs and we seem to use GCS, not AWS S3. That being said, we should make sure this is indeed the case. @jbuck WDYT?

If it is safe to remove S3/AWS support because it is unlikely to be used any time soon, we'll want to make sure that env variables like `S3_BUCKET`, `S3_PREFIX` and `AWS_REGION` are no longer supported.

**Comment by jbuck** [comment]
Yeah, I think it's safe to remove the AWS deps: https://github.com/mozilla-services/cloudops-infra/blob/master/projects/stubattribution/k8s/charts/stubattribution/templates/configmap.yaml#L16-L19
