### ISSUE TITLE
Add support for macOS attribution data

### ISSUE THREAD

**Issue by willdurand** [mozilla-services/stubattribution#147]
See: https://docs.google.com/document/d/1NLobogbVfSYofcm7b61tesTirlXpmxwIRYd6Gsd3tt8/edit#heading=h.hhe1o3e8alj5

---

We’re still settling on the exact details, but the stub attribution service will need to:

- Read the “koly” block of the DMG
- Use the “koly” block to read the XML plist of the DMG
- Parse a Mozilla-specific “attribution” XML element to determine offsets, sizes, partial checksums, etc.
- Replace the placeholder with new attribution details
- Compute new CRC32 checksums

This will likely require some internal refactoring since this project has been very Windows-oriented so far.

**Comment by ncalexan** [comment]
> This will likely require some internal refactoring since this project has been very Windows-oriented so far.

Aye.  Just setting this up to handle macOS would be a great first step -- i.e., adding support for some kind of processing based on the target OS, even if the macOS processing just passes through at first.

**Comment by bhearsum** [comment]
#187 landed the Go implementation of the dmg reading/modifying. @hneiva will be following up to wire that up to the actual service.

**Comment by willdurand** [comment]
It looks we're good here.
