### ISSUE TITLE
Allow any source values instead of replacing some with "(other)"

### ISSUE THREAD

**Issue by Mardak** [mozilla-services/stubattribution#169]
Originally [Bug 1827985 - Stub Attribution "source" replaces many values with (other)](https://bugzilla.mozilla.org/show_bug.cgi?id=1827985)

Seems like https://github.com/mozilla-services/stubattribution/blob/master/attributioncode/sourcewhitelist.go can be removed along with the callsites

Curious if we're able to see the logs of what has been filtered out? https://github.com/mozilla-services/stubattribution/blob/5657a24a396c69a92e951432f1479f72899c7164/attributioncode/validator.go#L178

**Comment by willdurand** [comment]
> Curious if we're able to see the logs of what has been filtered out?

I suppose we could, though IIRC I added the actual source recently.
