### ISSUE TITLE
Passing the timestamp parameter and its value causes Firefox to not parse attribution data

### ISSUE THREAD

**Issue by stephendonner** [mozilla-services/stubattribution#39]
We are now passing along the &timestamp= param and its value all the way to the client, and this is making Firefox not read in the postSigningData string.

Working:
<img width="1033" alt="screen shot 2016-12-21 at 4 21 37 pm" src="https://cloud.githubusercontent.com/assets/387249/21910482/0e03893c-d8d1-11e6-86c2-97d332ff85f0.png">

Failing:
<img width="1680" alt="screen shot 2017-01-12 at 1 30 33 pm" src="https://cloud.githubusercontent.com/assets/387249/21910492/1d8d89f2-d8d1-11e6-819c-a1b48358b581.png">

**Comment by stephendonner** [comment]
(Specifically, about:telemetry no longer shows the four entries for attribution.source, attribution.medium, attribution.campaign, and attribution.content under Environment Data -> Settings.)

**Comment by oremj** [comment]
Fixed in #40

**Comment by stephendonner** [comment]
Thx, verified!

<img width="1604" alt="screen shot 2017-01-12 at 3 24 37 pm" src="https://cloud.githubusercontent.com/assets/387249/21912600/e1a922e2-d8db-11e6-9762-6132d0f00361.png">
