### ISSUE TITLE
Non-whitelisted sources should be changed to (other) instead of ignored

### ISSUE THREAD

**Issue by oremj** [mozilla-services/stubattribution#57]
cc @chrismore

**Comment by chrismore** [comment]
Thanks for filing this @oremj !

**Comment by oremj** [comment]
@chrismore how does #58 look?

**Comment by chrismore** [comment]
Looks good to me @oremj.

**Comment by stephendonner** [comment]
FWIW, I'm also going to try writing a "negative" test to cover this missed (eek) scenario in my end-to-end WebDriver tests, in https://github.com/mozilla/stubattribution-tests/issues/23
