### ISSUE TITLE
Add mozilla.org to regex section of whitelist

### ISSUE THREAD

**Issue by hoosteeno** [mozilla-services/stubattribution#78]
We currently include several critical global domains in the regex section of the whitelist:

https://github.com/mozilla-services/stubattribution/blob/master/attributioncode/sourcewhitelist.go#L18

We even include everything at our testing domain, `*.allizom.org`, and everything at `*.firefox.com`. But we don't include our production domain, mozilla.org. That means any mozilla subdomain that wishes to drive attributed product downloads must request a one-off rule to be added to the whitelist. Example: blog.mozilla.org, which spent a great deal of 2017 driving downloads, is not on the list and so [we have no attribution data for it](https://sql.telemetry.mozilla.org/queries/52479/source?p_start_date_52479=20170118#139778).

Can we add `^[\w-]*\.mozilla\.org$` to the regex whitelist? We can remove one-off subdomains from the individual list of rules at the same time.

**Comment by chrismore** [comment]
@oremj ^^

**Comment by hoosteeno** [comment]
I hate to be a squeaky wheel, but not having attribution data for most mozilla.org sites makes it very difficult to talk about the impact of user download journeys on firefox user retention. And we have to do that in 2018. @oremj if I submit a PR for this would you be able to review it?

**Comment by hoosteeno** [comment]
https://github.com/mozilla-services/stubattribution/pull/79
