### ISSUE TITLE
Potential data length issue

### ISSUE THREAD

**Issue by pmac** [mozilla-services/stubattribution#82]
Hi,

We've noticed that certain campaigns are failing to make it into telemetry and I think I've found the answer to why. It seems that some of the campaigns put a long-ish string into `utm_campaign`, which results in a long base64 encoded string to send to the attribution service. I found that the attribution service rejects code strings of over 200 characters, which it turns out is easier to reach than I thought since that equates to a roughly 150 character decoded string. So I have two questions:

1) Do you see a lot of rejections in the logs for the code being too long (over 200 chars)?
2) Is it possible we could increase this limit?

Thanks!

**Comment by pmac** [comment]
For example:

This base64 encoded code (208 chars):

* c291cmNlPWFkbXJrdCZtZWRpdW09Y3BjJmNhbXBhaWduPUZpcmVmb3glN2NhZG1ya3QlN2NTZWFyY2glN2NDYXRlZ29yeSU3Y1NQJTdjVVMlN2NFTiU3Y0RLJTdjVGV4dCU3Y0NhdGVnb3J5JmNvbnRlbnQ9QTE0NF9BODI4X0MwMDg2ODYmdGltZXN0YW1wPTE1MzUwMzc4ODA.

Decodes to (155 chars):

* source=admrkt&medium=cpc&campaign=Firefox%7cadmrkt%7cSearch%7cCategory%7cSP%7cUS%7cEN%7cDK%7cText%7cCategory&content=A144_A828_C008686&timestamp=1535037880

Which is only 134 characters after removing the timestamp. That's from a real URL in one of our ad campaigns.

**Comment by pmac** [comment]
Any thoughts @oremj @matt-howell ?

**Comment by oremj** [comment]
Yeah, we have quite a few failures due to hitting the character limit, but even more due to expired timestamps. @pmac you can check out https://sentry.prod.mozaws.net/operations/stub_attribution-prod/ for more information. I just invited you.

**Comment by pmac** [comment]
Still can't see that project for now. Maybe it'll send me an email soon.

I've been wondering about the timestamps as well. I think they're probably overkill right? We could look at disabling them. Or, like Matt said, enforce the 200 character limit after b64 decoding and removing the timestamp from the data. That would get us around most of the limitation we're seeing (for now at least).

**Comment by oremj** [comment]
Yeah, that sounds good. I can't remember why we decided we need to expire these. If we ever need to invalidate everything, we can just change the hmac key.

**Comment by pmac** [comment]
> Yeah, that sounds good. I can't remember why we decided we need to expire these. If we ever need to invalidate everything, we can just change the hmac key.

Agreed. I remember something about wanting to prevent someone using bedrock to generate a whole lot of valid keys, then hitting the service all at once in an attempt to DOS... but that does seem a bit far-fetched.

**Comment by pmac** [comment]
I filed a PR for bedrock that will truncate data in `utm_campaign` if the code ends up being > 200 chars so that we don't drop these for now. But when these changes land in the attribution service I can remove or modify that.

**Comment by pmac** [comment]
After thinking about it some more my recommendation is:

1. Remove the timestamp check in the attribution service.
2. Move the code length check to after base64 decode.
3. After those changes are deployed I'll update bedrock to stop attaching a timestamp to the code.

That should both give us a decent amount more data we can send and remove the timestamp errors we're seeing. Sound good? If so would you like separate issues for those tasks?

**Comment by pmac** [comment]
Great! Thanks oremj. Shall I file separate issues for those? I may be able to submit some PRs for this today actually. Don't think it'd be that hard to do these things, though I'm not very familiar with Golang.

**Comment by oremj** [comment]
@pmac I've filed those issues.

**Comment by oremj** [comment]
This was resolved in #83 and #84.
